// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7UREARxF0O3qN5UEgQPAb8jUy_Lv9htk',
    appId: '1:869883656143:web:0e85fe89a63bab2b4e44ba',
    messagingSenderId: '869883656143',
    projectId: 'ecommerce-b44bc',
    authDomain: 'ecommerce-b44bc.firebaseapp.com',
    storageBucket: 'ecommerce-b44bc.appspot.com',
    measurementId: 'G-HCQ6VRV7EQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLyOayEFWxo9hRlesrtZ32ZnYFwmSiIrw',
    appId: '1:869883656143:android:7edff56f22ec1def4e44ba',
    messagingSenderId: '869883656143',
    projectId: 'ecommerce-b44bc',
    storageBucket: 'ecommerce-b44bc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKtHbINAltgJJD06F1v78biM-iKpu16nk',
    appId: '1:869883656143:ios:3748a025f2481bac4e44ba',
    messagingSenderId: '869883656143',
    projectId: 'ecommerce-b44bc',
    storageBucket: 'ecommerce-b44bc.appspot.com',
    androidClientId: '869883656143-1uh5tsas42diimp16g7cocbkbrg735qr.apps.googleusercontent.com',
    iosClientId: '869883656143-9rn1q1tbkv2h9fep4cvvupor0lgaif72.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatAppMax',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKtHbINAltgJJD06F1v78biM-iKpu16nk',
    appId: '1:869883656143:ios:3748a025f2481bac4e44ba',
    messagingSenderId: '869883656143',
    projectId: 'ecommerce-b44bc',
    storageBucket: 'ecommerce-b44bc.appspot.com',
    androidClientId: '869883656143-1uh5tsas42diimp16g7cocbkbrg735qr.apps.googleusercontent.com',
    iosClientId: '869883656143-9rn1q1tbkv2h9fep4cvvupor0lgaif72.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatAppMax',
  );
}
